version: '3.8'

services:
  # Основной сервис бота
  bot:
    build: .
    container_name: magnum-stars-bot
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - magnum-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bot health check')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # База данных MongoDB
  mongodb:
    image: mongo:6.0
    container_name: magnum-stars-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: magnum_stars
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - magnum-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB Express (веб-интерфейс для управления БД)
  mongo-express:
    image: mongo-express:latest
    container_name: magnum-stars-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - magnum-network
    restart: unless-stopped
    profiles:
      - dev

  # Redis для кеширования (опционально)
  redis:
    image: redis:7-alpine
    container_name: magnum-stars-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - magnum-network
    restart: unless-stopped
    profiles:
      - cache

  # Nginx для проксирования (опционально)
  nginx:
    image: nginx:alpine
    container_name: magnum-stars-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - bot
    networks:
      - magnum-network
    restart: unless-stopped
    profiles:
      - proxy

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  magnum-network:
    driver: bridge